package com.guberan.faq.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.ai.document.Document;
import org.springframework.ai.document.id.RandomIdGenerator;

import java.time.LocalDateTime;
import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class FaqDto {
    public static final String QUESTION_KEY = "question";
    public static final String VALIDATED_KEY = "validated";
    public static final String AUTO_GENERATED_KEY = "autoGenerated";
    public static final String ASKED_AT_KEY = "askedAt";
    public static final String SOURCE_KEY = "source";

    private String id;
    private String question;
    private String answer;
    private boolean validated;
    private boolean autoGenerated;
    private LocalDateTime askedAt;
    private List<ContextItemDto> contextItems;


    public FaqDto(String question, String answer) {
        this.id = new RandomIdGenerator().generateId();
        this.question = question;
        this.answer = answer;
        this.validated = false;
        this.autoGenerated = true;
        this.askedAt = LocalDateTime.now();
        this.contextItems = List.of();
    }

    public FaqDto(Document doc) {
        this.id = doc.getId();
        this.question = doc.getMetadata().get(QUESTION_KEY).toString();
        this.answer = doc.getText();
        this.validated = Boolean.TRUE.equals(doc.getMetadata().get(VALIDATED_KEY));
        this.autoGenerated = Boolean.TRUE.equals(doc.getMetadata().get(AUTO_GENERATED_KEY));
        this.askedAt = LocalDateTime.parse(String.valueOf(doc.getMetadata().get(ASKED_AT_KEY)));
    }

    public record ContextItemDto(String text, double score, String docId) {
    }
}