services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: pgvector-faq
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      # Uncomment if you want to initialize with schema.sql
      # - ./backend/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  backend:
    build: ./backend
    container_name: faq-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: faq-frontend
    ports:
      - "5173:80"  # Serve frontend on localhost:5173
    depends_on:
      - backend

volumes:
  pgdata:
    name: faq-pgvector-volume