package com.guberan.faq.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import lombok.*;

import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;

@Entity
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Getter
@Setter
public class Faq {

    @Id
    @Column(nullable = false, updatable = false)
    private UUID id;
    private String question;
    @Column(columnDefinition = "TEXT")
    private String answer;
    private boolean validated;
    private boolean autoGenerated;
    private LocalDateTime askedAt;
    private double confidenceScore;
    private List<String> snippets;

    public Faq(String question, String answer, boolean validated, boolean autoGenerated) {
        this.id = UUID.randomUUID();
        this.question = question;
        this.answer = answer;
        this.validated = validated;
        this.autoGenerated = autoGenerated;
        this.askedAt = LocalDateTime.now();
    }

    public Faq(String question, String answer, List<String> snippets) {
        this.id = UUID.randomUUID();
        this.question = question;
        this.answer = answer;
        this.validated = false;
        this.autoGenerated = true;
        this.askedAt = LocalDateTime.now();
        this.snippets = snippets;
    }

}