package com.guberan.faq.service;

import com.guberan.faq.dto.FaqDto;
import com.guberan.faq.model.Faq;
import com.guberan.faq.repository.FaqRepository;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.ai.chat.client.advisor.vectorstore.QuestionAnswerAdvisor;
import org.springframework.ai.chat.messages.AssistantMessage;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.chat.model.Generation;
import org.springframework.ai.document.Document;
import org.springframework.ai.vectorstore.SearchRequest;
import org.springframework.ai.vectorstore.VectorStore;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.bean.override.mockito.MockitoBean;
import org.springframework.transaction.support.TransactionTemplate;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;

@SpringBootTest
@ActiveProfiles("test")
class FaqServiceIT {

    @Autowired
    private FaqService faqService;

    @Autowired
    private FaqRepository faqRepository;

    @MockitoBean
    private ChatClient chatClient;

    @MockitoBean
    private VectorStore vectorStore;

    @Autowired
    private TransactionTemplate transactionTemplate;

    @Test
    void ask() {
        String question = "What is Spring AI?";
        String answer = "Spring AI is a framework...";

        // mock vector search
        Mockito.when(vectorStore.similaritySearch(any(SearchRequest.class)))
                .thenReturn(List.of(new Document("context")));

        // mock ChatClient fluent API
        ChatClient.ChatClientRequestSpec requestSpec = Mockito.mock(ChatClient.ChatClientRequestSpec.class);
        ChatClient.CallResponseSpec responseSpec = Mockito.mock(ChatClient.CallResponseSpec.class);

        Mockito.when(chatClient.prompt()).thenReturn(requestSpec);
        Mockito.when(requestSpec.system(anyString())).thenReturn(requestSpec);
        Mockito.when(requestSpec.advisors(any(QuestionAnswerAdvisor.class))).thenReturn(requestSpec);
        Mockito.when(requestSpec.user(anyString())).thenReturn(requestSpec);
        Mockito.when(requestSpec.call()).thenReturn(responseSpec);

        ChatResponse chatResponse = Mockito.mock(ChatResponse.class);
        Generation generation = Mockito.mock(Generation.class);
        AssistantMessage assistantMessage = Mockito.mock(AssistantMessage.class);

        Mockito.when(responseSpec.chatResponse()).thenReturn(chatResponse);
        Mockito.when(chatResponse.getResult()).thenReturn(generation);
        Mockito.when(generation.getOutput()).thenReturn(assistantMessage);
        Mockito.when(assistantMessage.getText()).thenReturn(answer);


        FaqDto result = faqService.ask(question);


        assertThat(result).isNotNull();
        assertThat(result.getQuestion()).isEqualTo(question);
        assertThat(result.getAnswer()).isEqualTo(answer);

        transactionTemplate.execute(status -> {
            Optional<Faq> saved = faqRepository.findById(UUID.fromString(result.getId()));
            assertThat(saved).isPresent();
            assertThat(saved.get().getQuestion()).isEqualTo(question);
            assertThat(saved.get().isValidated()).isFalse();
            return null;
        });
    }

    @Test
    @WithMockUser(roles = "ADMIN")
    void validateResponse() {

        Faq faq = new Faq("Q?", "Auto answer", List.of());
        faq = faqRepository.save(faq);
        faqRepository.flush();

        FaqDto dto = new FaqDto();
        dto.setId(faq.getId().toString());
        dto.setAnswer("Validated answer");


        FaqDto result = faqService.validateResponse(dto);

        assertThat(result.isValidated()).isTrue();
        assertThat(result.getAnswer()).isEqualTo("Validated answer");

        Faq updated = faqRepository.findById(UUID.fromString(result.getId())).orElseThrow();
        assertThat(updated.isValidated()).isTrue();
        assertThat(updated.isAutoGenerated()).isFalse();

        Mockito.verify(vectorStore, Mockito.atLeastOnce()).add(any(List.class));
    }

    @Disabled("turn on if you want to check the security")
    @Test
    @WithMockUser(roles = "USER")
    void validateResponseForNonAdminFails() {
        assertThatThrownBy(() -> faqService.validateResponse(new FaqDto()))
                .isInstanceOf(org.springframework.security.access.AccessDeniedException.class);
    }

    @Test
    @WithMockUser(roles = "ADMIN")
    void deleteFaq() {
        Faq faq = faqRepository.save(new Faq("Q?", "A", List.of()));
        UUID id = faq.getId();

        boolean deleted = faqService.deleteFaq(id);

        assertThat(deleted).isTrue();
        assertThat(faqRepository.existsById(id)).isFalse();
        Mockito.verify(vectorStore).delete(List.of(id.toString()));
    }

    @Disabled("turn on if you want to check the security")
    @Test
    @WithMockUser(roles = "USER")
    void deleteFaqForNonAdminFails() {
        Faq faq = faqRepository.save(new Faq("Q?", "A", List.of()));
        UUID id = faq.getId();

        assertThatThrownBy(() -> faqService.deleteFaq(id))
                .isInstanceOf(org.springframework.security.access.AccessDeniedException.class);
    }
}