package com.guberan.faq.mapper;

import com.guberan.faq.dto.FaqDto;
import com.guberan.faq.model.Faq;
import org.springframework.ai.document.Document;
import org.springframework.stereotype.Component;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;


@Component
public class FaqMapper {
    public static final String QUESTION_KEY = "question";
    public static final String VALIDATED_KEY = "validated";
    public static final String AUTO_GENERATED_KEY = "autoGenerated";
    public static final String ASKED_AT_KEY = "askedAt";
    public static final String SOURCE_KEY = "source";

    public FaqDto toDto(Document doc) {
        return new FaqDto(doc);
    }

    public FaqDto toDto(Faq faq) {
        return new FaqDto(String.valueOf(faq.getId()), faq.getQuestion(), faq.getAnswer(), faq.isValidated(), faq.isAutoGenerated(), faq.getAskedAt(), faq.getConfidenceScore(), faq.getSnippets());
    }

    public Faq toFaq(FaqDto dto) {
        return new Faq(UUID.fromString(dto.getId()), dto.getQuestion(), dto.getAnswer(), dto.isValidated(), dto.isAutoGenerated(), dto.getAskedAt(), dto.getConfidenceScore(), dto.getSnippets());
    }

    public Document toDocument(Faq faq) {
        Map<String, Object> metadata = new HashMap<>();
        metadata.put(QUESTION_KEY, faq.getQuestion());
        metadata.put(VALIDATED_KEY, faq.isValidated());
        metadata.put(AUTO_GENERATED_KEY, faq.isAutoGenerated());
        metadata.put(ASKED_AT_KEY, String.valueOf(faq.getAskedAt()));
        metadata.put(SOURCE_KEY, "user-input");
        return new Document(faq.getId().toString(), faq.getAnswer(), metadata);
    }

}
