package com.guberan.faq.dto;

import org.junit.jupiter.api.Test;
import org.springframework.ai.document.Document;

import java.time.LocalDateTime;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

class FaqDtoTest {

    @Test
    void testConstructorWithQuestionAndAnswer() {
        FaqDto dto = new FaqDto("What is AI?", "AI stands for Artificial Intelligence.");

        assertThat(dto.getId()).isNotNull();
        assertThat(dto.getQuestion()).isEqualTo("What is AI?");
        assertThat(dto.getAnswer()).isEqualTo("AI stands for Artificial Intelligence.");
        assertThat(dto.isValidated()).isFalse();
        assertThat(dto.isAutoGenerated()).isTrue();
        assertThat(dto.getConfidenceScore()).isEqualTo(0.0);
        assertThat(dto.getSnippets()).isEmpty();
    }

    @Test
    void testConstructorWithDocument() {
        Map<String, Object> metadata = Map.of(
                FaqDto.QUESTION_KEY, "What is Spring Boot?",
                FaqDto.VALIDATED_KEY, true,
                FaqDto.AUTO_GENERATED_KEY, false,
                FaqDto.ASKED_AT_KEY, LocalDateTime.now().toString()
        );

        Document doc = new Document("doc-id-123", "Spring Boot is a Java framework.", metadata);
        FaqDto dto = new FaqDto(doc);

        assertThat(dto.getId()).isEqualTo("doc-id-123");
        assertThat(dto.getQuestion()).isEqualTo("What is Spring Boot?");
        assertThat(dto.getAnswer()).isEqualTo("Spring Boot is a Java framework.");
        assertThat(dto.isValidated()).isTrue();
        assertThat(dto.isAutoGenerated()).isFalse();
        assertThat(dto.getAskedAt()).isNotNull();
    }
}