import {useEffect, useState} from 'react';
import axios from 'axios';
import {Accordion, Box, Button, Flex, Heading, Progress, Text, Textarea, VStack} from '@chakra-ui/react';
import {toaster} from "../components/ui/toaster";


interface FaqDto {
    id: string;
    question: string;
    answer: string;
    validated: boolean;
    autoGenerated: boolean;
    askedAt: string; // ISO string pour LocalDateTime
    confidenceScore: number;
    contextItems: {
        text: string;
        score: number;
    }[];
}

const apiUrl = import.meta.env.VITE_API_URL || '';

const AdminPage = () => {
    const [questions, setQuestions] = useState<FaqDto[]>([]);
    const [editedAnswers, setEditedAnswers] = useState<{ [id: string]: string }>({});

    useEffect(() => {
        axios
            .get(`${apiUrl}/faq?validated=false`)
            .then((res) => {
                const data: FaqDto[] = Array.isArray(res.data) ? res.data : [];
                setQuestions(data.slice().reverse());
            })
            .catch(() => toaster.create({description: 'Error fetching questions', type: 'error'}));
    }, []);

    const validateAnswer = (faq: FaqDto) => {
        const correctedAnswer = editedAnswers[faq.id] ?? faq.answer;
        const payload = {...faq, answer: correctedAnswer};

        axios
            .patch(`${apiUrl}/faq/validate`, payload)
            .then(() => {
                setQuestions((prev) => prev.filter((q) => q.id !== faq.id));
                toaster.create({description: 'Answer validated', type: 'success'});
            })
            .catch(() => toaster.create({description: 'Error validating', type: 'error'}));
    };

    const deleteQuestion = (id: string) => {
        axios
            .delete(`${apiUrl}/faq/${id}`)
            .then(() => {
                setQuestions((prev) => prev.filter((q) => q.id !== id));
                toaster.create({description: 'Question deleted', type: 'info'});
            })
            .catch(() => toaster.create({description: 'Error deleting question', type: 'error'}));
    };

    return (
        <Box>
            <Heading mb={4}>Admin Panel</Heading>
            <VStack gap={6} align="stretch">
                {questions.map((q) => (
                    <Box key={q.id} p={4} borderWidth="1px" borderRadius="md">
                        <Text fontWeight="bold">Q: {q.question}</Text>
                        <Textarea
                            mt={2}
                            minH="120px"
                            resize="vertical"
                            rows={Math.min(16, (editedAnswers[q.id] ?? q.answer).split("\n").length)}
                            defaultValue={q.answer}
                            onChange={(e) =>
                                setEditedAnswers({...editedAnswers, [q.id]: e.target.value})
                            }
                        />

                        <Button mt={2} colorPalette="teal" onClick={() => validateAnswer(q)}>
                            Validate
                        </Button>

                        <Button mt={2} ml={2} colorPalette="red" variant="subtle" onClick={() => deleteQuestion(q.id)}>
                            Delete
                        </Button>

                        <Box mt={4} pt={2}/>

                        {q.contextItems && q.contextItems.length > 0 && (

                            <Accordion.Root collapsible defaultValue={[]}>
                                <Accordion.Item value="context">
                                    <Accordion.ItemTrigger>
                                        <Box flex="1" textAlign="left" fontWeight="semibold">
                                            Context Items
                                        </Box>
                                        <Accordion.ItemIndicator/>
                                    </Accordion.ItemTrigger>

                                    <Accordion.ItemContent pb={4}>
                                        {q.contextItems.map((item, index) => (
                                            <Box
                                                key={index}
                                                mb={3}
                                                p={2}
                                                borderWidth="1px"
                                                borderRadius="md"
                                                bg="gray.50"
                                            >
                                                <Flex justify="space-between" alignItems="center" mb={1}>
                                                    <Text fontSize="sm" fontWeight="bold">
                                                        {index + 1}
                                                    </Text>

                                                    <Flex alignItems="center" gap={2}>
                                                        <Progress.Root value={item.score * 100} max={100} width="150px">
                                                            <Progress.Track h="6px" borderRadius="md">
                                                                <Progress.Range colorPalette="teal"/>
                                                            </Progress.Track>
                                                        </Progress.Root>

                                                        <Text fontSize="xs" color="teal.800">
                                                            {(item.score * 100).toFixed(2)}%
                                                        </Text>
                                                    </Flex>
                                                </Flex>

                                                <Text fontSize="sm" color="teal.800">
                                                    {item.text}
                                                </Text>
                                            </Box>
                                        ))}
                                    </Accordion.ItemContent>
                                </Accordion.Item>
                            </Accordion.Root>
                        )}
                    </Box>
                ))}

                {questions.length === 0 && <Text>No unvalidated questions ✨</Text>}
            </VStack>
        </Box>
    );
};

export default AdminPage;